version: '{build}'
platform:
  - x64
clone_depth: 1
max_jobs: 3
cache:
  - '%LOCALAPPDATA%\Composer'
  - '%LOCALAPPDATA%\Temp\Chocolatey'

install:
  # Enable Windows Update service, needed to install vcredist2015 (dependency of php)
  - ps: Set-Service wuauserv -StartupType Manual
  - choco config set cacheLocation %LOCALAPPDATA%\Temp\Chocolatey
  - choco install -y php --version %PHP_VERSION%
  - choco install -y composer
  - refreshenv
  - composer install --no-interaction --no-progress --no-suggest --prefer-dist
build: off
test_script:
  - drupal-check
